import type { ShelfNode } from '@/types';

export interface PasilloConfig {
  numero: number;
  nombre: string;
  /** Etiqueta corta para el indicador flotante sobre el croquis (ej. "Pintura & Merino"). */
  shortLabel: string;
  color: string;
  estantes: string[];
}

export const PASILLOS_CONFIG: PasilloConfig[] = [
  { numero: 1, nombre: 'Artesanías y Folclore', shortLabel: 'Artesanías', color: '#06b6d4', estantes: ['Estante A', 'Estante B'] },
  { numero: 2, nombre: 'Pintura Piurana', shortLabel: 'Pintura & Merino', color: '#f59e0b', estantes: ['Estante A', 'Estante B'] },
  { numero: 3, nombre: 'Escultura Virreinal', shortLabel: 'Escultura', color: '#a855f7', estantes: ['Estante A', 'Estante B'] },
  { numero: 0, nombre: 'Archivo y Depósito Técnico', shortLabel: 'Archivo', color: '#94a3b8', estantes: ['Bloque Servidor', 'Inferior 1', 'Inferior 2', 'Inferior 3', 'Inferior 4', 'Inferior 5'] },
];

// Coordenadas calibradas sobre los píxeles reales de las estanterías dibujadas
// en croquis-mvp.png (1024x858 nativo, escala 0.9375 -> canvas 960x804):
// pared izquierda = Pasillo 1, pared superior = Pasillo 2, pared derecha = Pasillo 3.
export const INITIAL_SHELVES: ShelfNode[] = [
  {
    id: 'shelf-p1-ea',
    pasillo: 1,
    estante: 'Estante A',
    code: 'P1-EA',
    name: 'Cerámica de Chulucanas',
    category: 'Artesanías y Folclore',
    description: 'Artesanías en cerámica, filigrana y textilería de la región Piura.',
    bookCount: 118,
    x: 5,
    y: 33,
    width: 61,
    height: 353,
    metadata: { color: '#06b6d4', lastUpdated: '2026-08-21T15:30:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p1-eb',
    pasillo: 1,
    estante: 'Estante B',
    code: 'P1-EB',
    name: 'Filigrana y Sombreros de Toquilla',
    category: 'Artesanías y Folclore',
    description: 'Filigrana de Catacaos y sombreros de paja toquilla de Simbilá.',
    bookCount: 87,
    x: 5,
    y: 386,
    width: 61,
    height: 354,
    metadata: { color: '#06b6d4', lastUpdated: '2026-08-21T15:30:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p2-ea',
    pasillo: 2,
    estante: 'Estante A',
    code: 'P2-EA',
    name: 'Pintura Piurana',
    category: 'Pintura Piurana',
    description: 'Óleos y acuarelas de la escuela pictórica de Piura.',
    bookCount: 142,
    x: 28,
    y: 14,
    width: 293,
    height: 122,
    metadata: { color: '#f59e0b', lastUpdated: '2026-08-21T15:30:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p2-eb',
    pasillo: 2,
    estante: 'Estante B',
    code: 'P2-EB',
    name: 'Colección Ignacio Merino',
    category: 'Pintura Piurana',
    description: 'Grabados, cartas y estudio del maestro Ignacio Merino.',
    bookCount: 96,
    x: 321,
    y: 14,
    width: 293,
    height: 122,
    metadata: { color: '#f59e0b', lastUpdated: '2026-08-21T15:30:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p3-ea',
    pasillo: 3,
    estante: 'Estante A',
    code: 'P3-EA',
    name: 'Escultura Virreinal',
    category: 'Escultura',
    description: 'Esculturas, retablos e imaginería del periodo virreinal.',
    bookCount: 74,
    x: 764,
    y: 202,
    width: 56,
    height: 269,
    metadata: { color: '#a855f7', lastUpdated: '2026-08-21T15:30:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p3-eb',
    pasillo: 3,
    estante: 'Estante B',
    code: 'P3-EB',
    name: 'Historia Regional',
    category: 'Historia Regional',
    description: 'Historia, arqueología y estudios regionales de Piura y el norte del Perú.',
    bookCount: 105,
    x: 764,
    y: 471,
    width: 56,
    height: 270,
    metadata: { color: '#a855f7', lastUpdated: '2026-08-21T15:30:00.000Z', updatedBy: 'system' },
  },
  // Bloque de estantería bajo el rack del servidor (esquina superior derecha del croquis real).
  {
    id: 'shelf-p0-servidor',
    pasillo: 0,
    estante: 'Bloque Servidor',
    code: 'ARCH-SRV',
    name: 'Depósito Técnico',
    category: 'Archivo Técnico',
    description: 'Estantería auxiliar junto al rack de red — material de archivo y consulta interna.',
    bookCount: 40,
    x: 615,
    y: 50,
    width: 140,
    height: 175,
    metadata: { color: '#94a3b8', lastUpdated: '2026-08-31T00:00:00.000Z', updatedBy: 'system' },
  },
  // Estantería de la pared inferior (5 módulos, visibles con placa identificadora en croquis-mvp.png).
  {
    id: 'shelf-p0-inf-1',
    pasillo: 0,
    estante: 'Inferior 1',
    code: 'ARCH-01',
    name: 'Sección General 1',
    category: 'Colección General',
    description: 'Módulo de estantería de la pared inferior — pendiente de asignación por el bibliotecario.',
    bookCount: 0,
    x: 47,
    y: 694,
    width: 100,
    height: 75,
    metadata: { color: '#94a3b8', lastUpdated: '2026-08-31T00:00:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p0-inf-2',
    pasillo: 0,
    estante: 'Inferior 2',
    code: 'ARCH-02',
    name: 'Sección General 2',
    category: 'Colección General',
    description: 'Módulo de estantería de la pared inferior — pendiente de asignación por el bibliotecario.',
    bookCount: 0,
    x: 155,
    y: 694,
    width: 100,
    height: 75,
    metadata: { color: '#94a3b8', lastUpdated: '2026-08-31T00:00:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p0-inf-3',
    pasillo: 0,
    estante: 'Inferior 3',
    code: 'ARCH-03',
    name: 'Sección General 3',
    category: 'Colección General',
    description: 'Módulo de estantería de la pared inferior — pendiente de asignación por el bibliotecario.',
    bookCount: 0,
    x: 263,
    y: 694,
    width: 100,
    height: 75,
    metadata: { color: '#94a3b8', lastUpdated: '2026-08-31T00:00:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p0-inf-4',
    pasillo: 0,
    estante: 'Inferior 4',
    code: 'ARCH-04',
    name: 'Sección General 4',
    category: 'Colección General',
    description: 'Módulo de estantería de la pared inferior — pendiente de asignación por el bibliotecario.',
    bookCount: 0,
    x: 371,
    y: 694,
    width: 100,
    height: 75,
    metadata: { color: '#94a3b8', lastUpdated: '2026-08-31T00:00:00.000Z', updatedBy: 'system' },
  },
  {
    id: 'shelf-p0-inf-5',
    pasillo: 0,
    estante: 'Inferior 5',
    code: 'ARCH-05',
    name: 'Sección General 5',
    category: 'Colección General',
    description: 'Módulo de estantería de la pared inferior — pendiente de asignación por el bibliotecario.',
    bookCount: 0,
    x: 479,
    y: 694,
    width: 100,
    height: 75,
    metadata: { color: '#94a3b8', lastUpdated: '2026-08-31T00:00:00.000Z', updatedBy: 'system' },
  },
];